apiVersion: v2
name: vkr-metachart
version: 4.0.0
appVersion: "1.0.0"
description: Helm metachart for configuration management of multiservice applications
keywords:
  - kubernetes
  - helm
  - metachart
  - configuration-management
  - multiservice
maintainers:
  - name: VKR project
    email: example@example.com
