global:
  environment: prod
  namespace: demo-app-prod

services:
  frontend:
    replicaCount: 3
    ingress:
      host: frontend.example.com
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 700m
        memory: 768Mi
  apiGateway:
    replicaCount: 3
    ingress:
      host: api.example.com
    resources:
      requests:
        cpu: 300m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1024Mi
  userService:
    replicaCount: 3
  orderService:
    replicaCount: 3
  notificationWorker:
    replicaCount: 2
