global:
  environment: stage
  namespace: demo-stage
  imageTag: stage

services:
  frontend:
    replicaCount: 2
    ingress:
      host: frontend.stage.local
  apiGateway:
    replicaCount: 2
    ingress:
      host: api.stage.local
  userService:
    replicaCount: 2
  orderService:
    replicaCount: 2
