global:
  environment: stage
  namespace: demo-app-stage

services:
  frontend:
    replicaCount: 2
    ingress:
      host: frontend.stage.local
  apiGateway:
    replicaCount: 2
    ingress:
      host: api.stage.local
  userService:
    replicaCount: 2
  orderService:
    replicaCount: 2
  notificationWorker:
    replicaCount: 1
