global:
  environment: dev
  namespace: demo-app
  imageTag: dev-local

services:
  frontend:
    replicaCount: 1
    ingress:
      host: frontend.local
  apiGateway:
    replicaCount: 1
    ingress:
      host: api.local
  userService:
    replicaCount: 1
  orderService:
    replicaCount: 1
  notificationWorker:
    replicaCount: 1
