serviceMesh:
  enabled: true
  provider: istio
  gateway:
    enabled: true
    hosts:
      - api.local
      - frontend.local

services:
  frontend:
    serviceMesh:
      virtualService:
        enabled: true
        hosts:
          - frontend.local
        pathPrefix: /
      destinationRule:
        enabled: true
  apiGateway:
    serviceMesh:
      virtualService:
        enabled: true
        hosts:
          - api.local
        pathPrefix: /
      destinationRule:
        enabled: true
