stages:
  - validate
  - render

variables:
  HELM_EXPERIMENTAL_OCI: "1"

helm_lint:
  image: alpine/helm:3.14.4
  stage: validate
  script:
    - helm lint chart

render_dev:
  image: alpine/helm:3.14.4
  stage: render
  script:
    - helm template demo chart -f chart/values-dev.yaml > rendered-dev.yaml
  artifacts:
    paths:
      - rendered-dev.yaml

render_prod:
  image: alpine/helm:3.14.4
  stage: render
  script:
    - helm template demo chart -f chart/values-prod.yaml > rendered-prod.yaml
  artifacts:
    paths:
      - rendered-prod.yaml
