global:
  environment: stage

services:
  frontend:
    replicaCount: 2
    ingress:
      host: frontend.stage.local
  apiGateway:
    replicaCount: 2
    ingress:
      host: api.stage.local
  userService:
    replicaCount: 2
    secret:
      stringData:
        DB_PASSWORD: stage-password
