global:
  environment: dev

services:
  frontend:
    ingress:
      host: frontend.local
  apiGateway:
    ingress:
      host: api.local
  userService:
    secret:
      stringData:
        DB_PASSWORD: dev-password
