global:
  namespace: demo-dev
  environment: dev
  imagePullPolicy: IfNotPresent

services:
  frontend:
    replicaCount: 1
    ingress:
      host: frontend.dev.local
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"
  apiGateway:
    replicaCount: 1
    ingress:
      host: api.dev.local
    env:
      LOG_LEVEL: debug
  userService:
    replicaCount: 1
    env:
      LOG_LEVEL: debug
  notificationWorker:
    replicaCount: 1
