{{- if and .Values.serviceMesh.enabled (eq .Values.serviceMesh.provider "istio") .Values.serviceMesh.gateway.enabled }}
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ printf "%s-%s" .Release.Name .Values.serviceMesh.gateway.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "meta-chart.namespace" . }}
  labels:
{{ include "meta-chart.serviceLabels" (dict "root" . "serviceName" "istio-gateway") | nindent 4 }}
spec:
  selector:
{{ toYaml .Values.serviceMesh.gateway.selector | nindent 4 }}
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
{{ toYaml .Values.serviceMesh.gateway.hosts | nindent 8 }}
{{- end }}
