{{- if and .Values.serviceMesh.enabled (eq .Values.serviceMesh.provider "istio") .Values.serviceMesh.gateway.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.serviceMesh.gateway.name }}
  namespace: {{ default (include "vkr.namespace" .) .Values.serviceMesh.gateway.namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
{{ toYaml .Values.serviceMesh.gateway.selector | indent 4 }}
  servers:
    - port:
        number: {{ .Values.serviceMesh.gateway.port }}
        name: http
        protocol: HTTP
      hosts:
{{ toYaml .Values.serviceMesh.gateway.hosts | indent 8 }}
{{- end }}
