{{- range $serviceName, $service := .Values.services }}
{{- if and $service.enabled $service.secret.enabled $service.secret.stringData }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vkr-metachart.serviceFullname" (dict "root" $ "serviceName" $serviceName) }}
  namespace: {{ include "vkr-metachart.namespace" $ | quote }}
  labels:
    {{- include "vkr-metachart.serviceLabels" (dict "root" $ "serviceName" $serviceName) | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := $service.secret.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
